<nav>
        <div>
            <a href="index.php" class="logo">
                <img src="./img/logo.png" alt="logo image">
            </a>
            
            <a class="nav-options" href="index.php">Home</a>
            <a class="nav-options" href="add.php">Add</a>
            <a class="nav-options" href="gallery.php">Gallery</a>
            <a class="nav-options" href="hikes.php">Hikes</a>
            
        </div>


        
        <div class="search-bar-container">
            <form class="search-bar-container">
                <input type="search" id="search-bar" placeholder="Search">
                <span class="material-symbols-outlined">
                    search
                </span>
                

            </form>
        </div>

        <div class="burger-icon">
            <span class="material-symbols-outlined">
                menu
            </span>
        </div>
    </nav>